name: dart_clinic
description: A hospital management system (CLI) built with Dart + SQLite.
version: 1.0.0

environment:
  sdk: ^3.9.2

dependencies:
  path: ^1.9.0              # File and path handling utilities
  prompts: ^2.0.0           # For user input (interactive CLI)
  uuid: ^4.4.0              # For unique ID generation
  crypto: ^3.0.5           # For password hashing

dev_dependencies:
  lints: ^6.0.0             # Dart style linter
  test: ^1.25.6             # Testing framework
  build_runner: ^2.4.6      # For code generation
  json_serializable: ^6.7.1 # Generates JSON <-> object conversions
